# Generated by Django 4.2 on 2024-07-17 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookshowed_bookdownloaded'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookshowed',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.category'),
        ),
        migrations.AlterField(
            model_name='bookshowed',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
