# Generated by Django 4.2 on 2024-07-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'required': 'Email kiritilmagan', 'unique': 'Bu email mavjud'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(error_messages={'required': 'Firstname kiritilmagan'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(error_messages={'required': 'Lastname kiritilmagan'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'required': 'Username kiritilmagan', 'unique': 'Bu user name mavjud'}, max_length=30, unique=True, verbose_name='username'),
        ),
    ]
